### ISSUE TITLE
Will this project be continued ?

### ISSUE THREAD

**Issue by codebanesr** [jdrouet/tekitoi#98]
I've been keeping an eye on this project for a while now, and it appears to have been inactive for quite some time.

**Comment by jdrouet** [comment]
I wish but I like of time and bandwidth 😓

**Comment by jdrouet** [comment]
I'd be happy to read about your requirements though. Tell me what you expect 😉

**Comment by codebanesr** [comment]
Sorry for the late reply. My requirements are the following - 
1. use oauth2 to get user credentials (support for multiple oauth providers), example screenshot
<img width="750" alt="Screenshot 2023-12-20 at 12 34 29 AM" src="https://github.com/jdrouet/tekitoi/assets/17947802/5c7ea3f0-7cc7-434c-9c1e-42b494ce6501">
2. ability to pass tokens to downstream servers

**Comment by jdrouet** [comment]
I restarted the project. I'm focusing on testing for now.
